spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Study/AIKU/aikuDb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        show_sql: true   # 하이버네이트 기본 SQL 출력 옵션
        format_sql: true # 하이버네이트 기본 SQL 포맷팅 옵션
  show-sql: true # JPA 쿼리를 콘솔에 출력

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
