spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: aiku-main-user
          uri: http://localhost:8081
          predicates:
            - Path=/users,/user/nickname
        - id: aiku-main-login
          uri: http://localhost:8081
          predicates:
            - Path=/login/sign-in
        - id: aiku-main
          uri: http://localhost:8081
          predicates:
            - Path=/users/**,/term,/groups/**,/schedules/**
        - id: aiku-map
          uri: http://localhost:8082
          predicates:
            - Path=/map/**

jwt:
  secret: ${JWT_SECRET}

custom:
  password: ${CUSTOM_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG