spring:
  cloud:
    gateway:
      routes:
        - id: aiku-main-user
          uri: http://localhost:8081
          predicates:
            - Path=/users,/user/nickname
        - id: aiku-main-login
          uri: http://localhost:8081
          predicates:
            - Path=/login/**
        - id: aiku-main
          uri: http://localhost:8081
          predicates:
            - Path=/users/**,/term,/groups/**,/schedules/**
        - id: aiku-map
          uri: http://localhost:8082
          predicates:
            - Path=/map/**