spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: aiku-main
          uri: http://3.36.57.4:8080
          predicates:
            - Path=/login/sign-in,/users/**,/term,/groups/**,/schedules/**,/member/schedules
        - id: aiku-map
          uri: http://43.203.205.111:8080
          predicates:
            - Path=/map/**

jwt:
  secret: ${JWT_SECRET}

custom:
  password: ${CUSTOM_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG