spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #주의 사용에 따라 create, update 사용 후 none으로 변경해주세요
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
#        show_sql: true   # 하이버네이트 기본 SQL 출력 옵션
#        format_sql: true # 하이버네이트 기본 SQL 포맷팅 옵션

firebase:
  config:
    type: ${FIREBASE_TYPE}
    project_id: ${FIREBASE_PROJECT_ID}
    private-key-id: ${FIREBASE_KEY_ID}
    private-key: ${FIREBASE_KEY}
    client-email: ${FIREBASE_EMAIL}
    client-id: ${FIREBASE_CLIENT_ID}
    auth-uri: ${FIREBASE_AUTH_URI}
    token-uri: ${FIREBASE_TOKEN_URI}
    auth-provider-x509-cert-url: ${FIREBASE_AUTH_PROVIDER}
    client-x509-cert-url: ${FIREBASE_CERT_URL}
    universe-domain: ${FIREBASE_UNIVERSE_DOMAIN}


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ, Asia/Seoul} [%X{request_id}] %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: /spring-log/application.log
