spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Study/AIKU/aikuDb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        show_sql: true   # 하이버네이트 기본 SQL 출력 옵션
        format_sql: true # 하이버네이트 기본 SQL 포맷팅 옵션

# TODO : 테스트용, 추후 환경변수로 변경 예정
jwt:
  secret: b7e29d7bc4c8704077549d755d01139de165e4bde39bbb16275c773250823125

custom.password: randomExamplePwd

kakao:
  base_url: https://kauth.kakao.com
  app_id: a9e9a269edb3f5aead5264bb3a505ac1

logging:
  level:
    root: INFO
