name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Start MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        mysql version: '8.0'
        mysql database: 'aiku'
        mysql root password: ${{ secrets.MYSQL_PASSWORD }}
        
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Create test/resources/application.yml
      run: |
        mkdir -p aiku/aiku-main/src/test/resources
        echo "${{ secrets.AIKU_MAIN_TEST_CONFIG }}" > aiku/aiku-main/src/test/resources/application.yml
        mkdir -p aiku/aiku-alarm/src/test/resources
        echo "${{ secrets.AIKU_ALARM_TEST_CONFIG }}" > aiku/aiku-alarm/src/test/resources/application.yml
        mkdir -p aiku/aiku-map/src/test/resources
        echo "${{ secrets.AIKU_MAP_TEST_CONFIG }}" > aiku/aiku-map/src/test/resources/application.yml

    - name: Build with Gradle Wrapper
      working-directory: aiku
      env:
        AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_SECRET: ${{ secrets.AWS_SECRET }}
        CUSTOM_PASSWORD: ${{ secrets.CUSTOM_PASSWORD }}
        GMAIL_ACCOUNT: ${{ secrets.GMAIL_ACCOUNT }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        KAKAO_APP_ID: ${{ secrets.KAKAO_APP_ID }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_URL: ${{ secrets.MYSQL_URL }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        KAFKA_SERVER_URL: ${{ secrets.KAFKA_SERVER_URL }}
        AIKU_MAIN_IP: ${{ secrets.AIKU_MAIN_IP }}
        AIKU_MAP_IP: ${{ secrets.AIKU_MAP_IP }}
      run: ./gradlew build
